(function attachDashboardDom(root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  root.DashboardDom = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function createDashboardDom() {
  'use strict';

  const REQUIRED_ELEMENT_IDS = Object.freeze([
    'manager-metadata-status',
    'tags-heading',
    'new-tag-btn',
    'tags-list',
    'tags-empty',
    'manager-view-filter',
    'manager-view-help',
    'tag-filter',
    'save-update-btn',
    'save-update-btn-reason',
    'add-to-collection-btn-reason',
    'tag-selected-btn',
    'tag-selected-btn-reason',
    'analyze-selected-btn',
    'analyze-selected-btn-reason',
    'summarize-selected-btn',
    'summarize-selected-btn-reason',
    'merge-selected-btn',
    'merge-selected-btn-reason',
    'move-selected-btn',
    'move-selected-btn-reason',
    'delete-selected-btn-reason',
    'remove-tag-btn',
    'tag-modal',
    'tag-modal-title',
    'tag-modal-copy',
    'tag-modal-select',
    'tag-modal-name',
    'tag-modal-status',
    'tag-modal-cancel-btn',
    'tag-modal-confirm-btn',
    'sync-btn',
    'history-load-btn',
    'history-rebuild-btn',
    'history-recover-search-btn',
    'history-maximum-input',
    'history-status',
    'history-inventory-status',
    'advanced-toggle-btn',
    'advanced-toggle-icon',
    'advanced-panel',
    'runtime-build-marker',
    'search-queries-input',
    'search-sync-btn',
    'search-sync-cancel-btn',
    'search-status',
    'search-sync-status',
    'diagnostic-query-input',
    'diagnostic-pages-select',
    'diagnostic-run-btn',
    'diagnostic-copy-btn',
    'diagnostic-status',
    'eligibility-verify-batch-btn',
    'eligibility-cancel-btn',
    'eligibility-copy-btn',
    'eligibility-status',
    'clear-db-btn',
    'inventory-count',
    'collections-section',
    'collections-list',
    'collections-empty',
    'new-collection-btn',
    'collection-filter',
    'search-input',
    'type-filter',
    'updated-from',
    'updated-to',
    'status-filter',
    'sort-title-header',
    'sort-title-icon',
    'sort-type-header',
    'sort-type-icon',
    'sort-updated-header',
    'sort-updated-icon',
    'select-all-checkbox',
    'chat-list-body',
    'empty-state',
    'action-banner',
    'selected-count-text',
    'deselect-btn',
    'add-to-collection-btn',
    'remove-from-collection-btn',
    'delete-selected-btn',
    'active-jobs-section',
    'active-job-card',
    'active-job-title',
    'active-job-status',
    'active-job-next',
    'active-job-timing',
    'active-job-error',
    'active-job-pause-btn',
    'active-job-resume-btn',
    'active-job-review-btn',
    'active-job-cancel-btn',
    'active-job-view-btn',
    'recent-activity-section',
    'recent-job-title',
    'recent-job-status',
    'recent-job-timing',
    'recent-job-dismiss-btn',
    'fixed-job-bar',
    'fixed-job-summary',
    'fixed-job-timing',
    'fixed-job-pause-btn',
    'fixed-job-resume-btn',
    'fixed-job-details-btn',
    'collection-modal',
    'collection-modal-title',
    'collection-modal-copy',
    'collection-modal-select',
    'collection-modal-name',
    'collection-modal-status',
    'collection-modal-cancel-btn',
    'collection-modal-confirm-btn',
    'progress-modal',
    'delete-confirm-panel',
    'delete-stage-indicator',
    'delete-prepare-panel',
    'delete-prepare-status',
    'delete-review-panel',
    'delete-review-standalone',
    'delete-review-project',
    'delete-review-custom-gpt',
    'delete-review-unresolved',
    'retry-unresolved-btn',
    'exclude-unresolved-btn',
    'exclude-custom-gpt-btn',
    'delete-start-panel',
    'delete-fast-timing-warning',
    'delete-start-back-btn',
    'delete-review-continue-btn',
    'modal-title',
    'delete-confirm-copy',
    'delete-plan-summary',
    'delete-preflight-status',
    'delete-project-warning',
    'delete-project-list',
    'approve-projects-btn',
    'remove-blocked-btn',
    'delete-interval-input',
    'delete-interval-status',
    'cancel-delete-confirm-btn',
    'confirm-delete-btn'
  ]);

  function bindDashboardElements(documentImpl) {
    if (!documentImpl || typeof documentImpl.getElementById !== 'function') {
      throw new TypeError('document must provide getElementById');
    }
    return Object.fromEntries(REQUIRED_ELEMENT_IDS.map(id => {
      const element = documentImpl.getElementById(id);
      if (!element) throw new Error(`Missing required dashboard element: ${id}`);
      return [id, element];
    }));
  }

  return { REQUIRED_ELEMENT_IDS, bindDashboardElements };
});
